name: molml
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ase
  - matplotlib
  - monty
  - numpy
  - openbabel
  - pip
  - plotly
  - pre-commit
  - pymatgen
  - mamba
  - basis_set_exchange
  - pymongo
  - scipy