channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ase
  - matplotlib
  - monty
  - numpy
  - openbabel
  - pip
  - plotly
  - pre-commit
  - pymatgen
  - pytorch
  - pip:
      - basis-set-exchange
      - chemcoord
      - e3nn
      - pymongo
      - scipy
      - torch-cluster
      - torch-geometric
      - torch-scatter
      - torch-sparse
      - torch-spline-conv
      - wandb
      - pyscf