name: molml
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
  - pyg
dependencies:
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - pyg
  - ase
  - matplotlib
  - monty
  - numpy
  - openbabel
  - pip
  - plotly
  - pre-commit
  - pymatgen
  - pip:
      - basis-set-exchange
      - chemcoord
      - pymongo
      - scipy
      - torch-cluster
      - torch-scatter
      - torch-sparse
      - torch-spline-conv
      - e3nn
      - wandb
      - pyscf