name: molml
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ase
  - matplotlib
  - monty
  - numpy
  - openbabel
  - pip
  - plotly
  - pre-commit
  - pymatgen
  - pip:
      - basis-set-exchange
      - chemcoord
      - pymongo
      - scipy
      - pyscf