---
dataset_options:
  minimal_basis:
    idx_eigenvalue: 0
    reactant_tag: "reactant"
    product_tag: "product"
    transition_state_tag: "transition_state"
  full_basis:
    idx_eigenvalue: 0
    reactant_tag: "reactant"
    product_tag: "product"
    transition_state_tag: "transition_state"

model_options:
  relative_energy:
    minimal_basis:
      irreps_node_attr: "1x0e"
      irreps_edge_attr: "@construct"
      radial_layers: 2
      radial_neurons: 64
      max_radius: 5
      num_basis: 12
      num_neighbors: 4
      typical_number_of_nodes: 12
      reduce_output: true 
      reference_reduced_output_to_initial_state: true
      make_absolute: false 
      mask_extra_basis: true
      normalize_sumsq: true
    full_basis:
      irreps_node_attr: "1x0e"
      irreps_edge_attr: "@construct"
      radial_layers: 2
      radial_neurons: 64
      max_radius: 5
      num_basis: 12
      num_neighbors: 4
      typical_number_of_nodes: 12
      reduce_output: true 
      reference_reduced_output_to_initial_state: true
      make_absolute: false 
      mask_extra_basis: true
      normalize_sumsq: true
  coeff_matrix:
    minimal_basis:
      irreps_node_attr: "1x0e"
      irreps_edge_attr: "@construct"
      radial_layers: 2
      radial_neurons: 64
      max_radius: 5
      num_basis: 12
      num_neighbors: 4
      typical_number_of_nodes: 12
      reduce_output: false
      make_absolute: false 
      mask_extra_basis: true
      normalize_sumsq: true
    full_basis:
      irreps_hidden: "64x0e+288x1o+64x2e"
      irreps_node_attr: "1x0e"
      irreps_edge_attr: "@construct"
      radial_layers: 2
      radial_neurons: 64
      max_radius: 5
      num_basis: 12
      num_neighbors: 4
      typical_number_of_nodes: 12
      reduce_output: false
      make_absolute: false 
      mask_extra_basis: true
      normalize_sumsq: true