---
filter_collection: 
  task_label: "single point"
identifier: "rxn_number"
state_identifier: "state"
reactant_tag: "reactant"
product_tag: "product"
transition_state_tag: "transition_state"
basis_set_name: "def2-msvp"
basis_set_type: "minimal"
d_functions_are_spherical: true 
