---
filter_collection: 
  "input.job_type": "sp"
  "tags.inverted_coordinates": true
identifier: "idx"
state_identifier: "state"
reactant_tag: "reactant"
product_tag: "product"
transition_state_tag: "transition_state"
basis_set_name: "6-31g*"
basis_set_type: "full"
d_functions_are_spherical: true 