---
filter_collection: 
  "input.job_type": "sp"
  "tags.reaction_name": "e2"
identifier: "rxn_number"
state_identifier: "state"
reactant_tag: "perturbed_molecule_-0_5_molecule"
product_tag: "perturbed_molecule_0_5_molecule"
transition_state_tag: "transition_state_molecule"
basis_set_name: "6-31g*"
basis_set_type: "minimal"
d_functions_are_spherical: false
