---
filter_collection: 
  "input.job_type": "sp"
  "tags.reaction_name": "sn2"
identifier: "rxn_number"
state_identifier: "state"
reactant_tag: "perturbed_molecule_-0_5_molecule"
product_tag: "perturbed_molecule_0_5_molecule"
transition_state_tag: "transition_state_molecule"
