---
dataset_options:
  minimal_basis:
    idx_eigenvalue: 0
    reactant_tag: "perturbed_molecule_-0_5_molecule"
    product_tag: "perturbed_molecule_0_5_molecule"
    transition_state_tag: "transition_state_molecule"
  full_basis:
    idx_eigenvalue: 0
    reactant_tag: "perturbed_molecule_-0_5_molecule"
    product_tag: "perturbed_molecule_0_5_molecule"
    transition_state_tag: "transition_state_molecule"
  
model_options:
  relative_energy:
    max_radius: 5
    num_neighbors: 4
    typical_number_of_nodes: 12
    layers: 4
    reduce_output: true 
    mask_extra_basis: true
    normalize_sumsq: true
    reference_reduced_output_to_initial_state: true
  coeff_matrix:
    max_radius: 5
    num_neighbors: 4
    typical_number_of_nodes: 12
    layers: 4
    reduce_output: false
    mask_extra_basis: true
    normalize_sumsq: true