---
json_filenames:
  minimal_basis:
    test_json: "input/rudorff_lilienfeld_sn2_dataset_minimal_basis_test.json"
    train_json: "input/rudorff_lilienfeld_sn2_dataset_minimal_basis_train.json"
    validate_json: "input/rudorff_lilienfeld_sn2_dataset_minimal_basis_validate.json"
    debug_test_json: "input/rudorff_lilienfeld_sn2_dataset_minimal_basis_test_debug.json"
    debug_train_json: "input/rudorff_lilienfeld_sn2_dataset_minimal_basis_train_debug.json"
    debug_validate_json: "input/rudorff_lilienfeld_sn2_dataset_minimal_basis_validate_debug.json"
  full_basis:
    test_json: "input/rudorff_lilienfeld_sn2_dataset_full_basis_test.json"
    train_json: "input/rudorff_lilienfeld_sn2_dataset_full_basis_train.json"
    validate_json: "input/rudorff_lilienfeld_sn2_dataset_full_basis_validate.json"
    debug_test_json: "input/rudorff_lilienfeld_sn2_dataset_full_basis_test_debug.json"
    debug_train_json: "input/rudorff_lilienfeld_sn2_dataset_full_basis_train_debug.json"
    debug_validate_json: "input/rudorff_lilienfeld_sn2_dataset_full_basis_validate_debug.json"

basis_options:
  filename: "input/6-31gstar.json"

dataset_options:
  minimal_basis:
    max_s_functions: 5
    max_p_functions: 4
    max_d_functions: 0
    idx_eigenvalue: 0
    reactant_tag: "perturbed_molecule_-0_5_molecule"
    product_tag: "perturbed_molecule_0_5_molecule"
    transition_state_tag: "transition_state_molecule"
  full_basis:
    max_s_functions: 5
    max_p_functions: 4
    max_d_functions: 3
    idx_eigenvalue: 0
    reactant_tag: "perturbed_molecule_-0_5_molecule"
    product_tag: "perturbed_molecule_0_5_molecule"
    transition_state_tag: "transition_state_molecule"

learning_options:
  batch_size: 16
  learning_rate: 0.01
  epochs: 250

model_options:
  relative_energy:
    minimal_basis:
      irreps_in: "@construct"
      irreps_hidden: "64x0e+288x1o"
      irreps_out: "@construct"
      irreps_node_attr: "1x0e"
      irreps_edge_attr: "@construct"
      radial_layers: 2
      radial_neurons: 64
      max_radius: 5
      num_basis: 12
      num_neighbors: 4
      typical_number_of_nodes: 12
      reduce_output: true 
      reference_reduced_output_to_initial_state: true
      make_absolute: false 
      mask_extra_basis: true
      normalize_sumsq: true
    full_basis:
      irreps_in: "@construct"
      irreps_hidden: "64x0e+288x1o+64x2e"
      irreps_out: "@construct"
      irreps_node_attr: "1x0e"
      irreps_edge_attr: "@construct"
      radial_layers: 2
      radial_neurons: 64
      max_radius: 5
      num_basis: 12
      num_neighbors: 4
      typical_number_of_nodes: 12
      reduce_output: true 
      reference_reduced_output_to_initial_state: true
      make_absolute: false 
      mask_extra_basis: true
      normalize_sumsq: true
  coeff_matrix:
    minimal_basis:
      irreps_in: "@construct"
      irreps_hidden: "64x0e+288x1o"
      irreps_out: "@construct"
      irreps_node_attr: "1x0e"
      irreps_edge_attr: "@construct"
      radial_layers: 2
      radial_neurons: 64
      max_radius: 5
      num_basis: 12
      num_neighbors: 4
      typical_number_of_nodes: 12
      reduce_output: false
      make_absolute: false 
      mask_extra_basis: true
      normalize_sumsq: true
    full_basis:
      irreps_in: "@construct"
      irreps_hidden: "64x0e+288x1o+64x2e"
      irreps_out: "@construct"
      irreps_node_attr: "1x0e"
      irreps_edge_attr: "@construct"
      radial_layers: 2
      radial_neurons: 64
      max_radius: 5
      num_basis: 12
      num_neighbors: 4
      typical_number_of_nodes: 12
      reduce_output: false
      make_absolute: false 
      mask_extra_basis: true
      normalize_sumsq: true