---
test_json: "/lustre/eaglefs/projects/silimorphous/svijay/projects/18_SEI/minimal-basis/training/input_files/test_data_interp_minimal_basis.json" 
train_json: "/lustre/eaglefs/projects/silimorphous/svijay/projects/18_SEI/minimal-basis/training/input_files/train_data_interp_minimal_basis.json" 
validate_json: "/lustre/eaglefs/projects/silimorphous/svijay/projects/18_SEI/minimal-basis/training/input_files/validate_data_interp_minimal_basis.json" 
batch_size: 10
learning_rate: 0.001
epochs: 250
basis_file: "/lustre/eaglefs/projects/silimorphous/svijay/projects/18_SEI/minimal-basis/training/input_files/6-31G_star.json"
irreps_out: "1x0e + 3x1o + 5x2e"