---
train_json: 
test_json: 
validate_json: 
batch_size: 10
learning_rate: 0.001
epochs: 250
basis_file: "/pscratch/sd/s/svijay/projects/18_SEI/minimal-basis/training/input_files/sto-3g.json"
irreps_out: "1x0e + 3x1o + 5x2e"