---
train_json: "/pscratch/sd/s/svijay/projects/18_SEI/minimal-basis/training/input_files/train_QMrxn20.json"
test_json: "/pscratch/sd/s/svijay/projects/18_SEI/minimal-basis/training/input_files/test_QMrxn20.json"
validate_json: "/pscratch/sd/s/svijay/projects/18_SEI/minimal-basis/training/input_files/validate_QMrxn20.json"
debug_train_json: "/pscratch/sd/s/svijay/projects/18_SEI/minimal-basis/training/input_files/train_debug_QMrxn20.json"
debug_test_json: "/pscratch/sd/s/svijay/projects/18_SEI/minimal-basis/training/input_files/test_debug_QMrxn20.json"
debug_validate_json: "/pscratch/sd/s/svijay/projects/18_SEI/minimal-basis/training/input_files/validate_debug_QMrxn20.json"
graph_generation_method: "sn2"
batch_size: 10
learning_rate: 0.001
epochs: 250
basis_file: "/pscratch/sd/s/svijay/projects/18_SEI/minimal-basis/training/input_files/sto-3g.json"