---
test_json: "input_files/test_data_interp_minimal_basis.json" 
train_json: "input_files/train_data_interp_minimal_basis.json" 
validate_json: "input_files/validate_data_interp_minimal_basis.json" 
debug_test_json: "input_files/debug_test_data_interp_minimal_basis.json" 
debug_train_json: "input_files/debug_train_data_interp_minimal_basis.json" 
debug_validate_json: "input_files/debug_validate_data_interp_minimal_basis.json" 
basis_file: "input_files/6-31G_star.json"
batch_size: 16 
learning_rate: 0.01
epochs: 500
irreps_hidden: "1x0e+1x1o"
irreps_in: "1x0e+1x1o"
irreps_out: "1x0e+1x1o"
irreps_node_attr: "1x0e"
radial_layers: 2
radial_neurons: 64
max_radius: 3
num_basis: 12
num_neighbors: 4
