---
test_json: "input_files/test_data_interp_minimal_basis.json" 
train_json: "input_files/train_data_interp_minimal_basis.json" 
validate_json: "input_files/validate_data_interp_minimal_basis.json" 
debug_test_json: "input_files/debug_test_data_interp_minimal_basis.json" 
debug_train_json: "input_files/debug_train_data_interp_minimal_basis.json" 
debug_validate_json: "input_files/debug_validate_data_interp_minimal_basis.json" 
basis_file: "input_files/6-31G_star.json"
batch_size: 16 
learning_rate: 0.01
epochs: 250
max_s_functions: 5
max_p_functions: 4
max_d_functions: 3
irreps_node_attr: "1x0e"
radial_layers: 2
radial_neurons: 64
max_radius: 5 
num_basis: 12
num_neighbors: 4
# irreps_hidden: "16x0e+288x1e+144x2e"
irreps_hidden: "16x0e+32x1e+16x2e"
prediction_mode: "forces"
irreps_out: '1x1e'
# prediction_mode: "coeff_matrix"
#prediction_mode: "relative_energy"
# use_minimal_basis_node_features: true
use_minimal_basis_node_features: false
