---
test_json: "input_files/test_data_interp_minimal_basis.json" 
train_json: "input_files/train_data_interp_minimal_basis.json" 
validate_json: "input_files/validate_data_interp_minimal_basis.json" 
debug_test_json: "input_files/debug_test_data_interp_minimal_basis.json" 
debug_train_json: "input_files/debug_train_data_interp_minimal_basis.json" 
debug_validate_json: "input_files/debug_validate_data_interp_minimal_basis.json" 
basis_file: "input_files/6-31G_star.json"

batch_size: 16
learning_rate: 0.01
epochs: 250

dataset_options:
  max_s_functions: 5
  max_p_functions: 4
  max_d_functions: 3
  idx_eigenvalue: 0

# use_minimal_basis_node_features: true
use_minimal_basis_node_features: false

#prediction_mode: "forces"
#irreps_out: '1x1o'
#irreps_hidden: "16x0e+288x1o+144x2e"

prediction_mode: "relative_energy"
model_options:
  irreps_in: "@construct"
  irreps_hidden: "64x0e+64x1o+32x2e"
  irreps_out: "@construct"
  irreps_node_attr: "1x0e"
  irreps_edge_attr: "@construct"
  radial_layers: 5
  radial_neurons: 8
  max_radius: 3
  num_basis: 16
  num_neighbors: 4
  typical_number_of_nodes: 12
  reduce_output: true 
  reference_reduced_output_to_initial_state: true
  make_absolute: false 
  mask_extra_basis: true
  normalize_sumsq: true

prediction_mode: "coeff_matrix"
model_options:
  irreps_in: "@construct"
  irreps_hidden: "64x0e+64x1o+32x2e"
  irreps_out: "@construct"
  irreps_node_attr: "1x0e"
  irreps_edge_attr: "@construct"
  radial_layers: 2
  radial_neurons: 64
  max_radius: 5
  num_basis: 12
  num_neighbors: 4
  typical_number_of_nodes: 12
  reduce_output: false
  make_absolute: true 
  mask_extra_basis: true
  normalize_sumsq: true
