name: Tests 

on:
  push:
    branches: [ main ] 
  pull_request:
    branches:
      - "feature/*"

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: coeffnet 
        environment-file: environment.yml
    
    - name: Install pytorch dependencies
      shell: bash -l {0}
      run: |
        mamba install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 -c pytorch -c conda-forge
        mamba install pyg -c pyg
        mamba install pytorch-scatter -c pyg
        mamba install pytorch-cluster -c pyg
    
    - name: Install requirements.txt
      shell: bash -l {0}
      run: |
        pip install -r requirements.txt

    - name: Install current package 
      shell: bash -l {0}
      run: |
        pip install .
    
    - name: Install test dependencies 
      shell: bash -l {0}
      run: |
        pip install -r requirements-test.txt

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest