name: Python package

on: [push]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: molml
        environment-file: environment.yml

    - name: Install current package 
      run: |
        pip install -e .

    - name: Test with pytest
      run: |
        conda install pytest
        pytest